### ISSUE TITLE
修改建议

### ISSUE THREAD

**Issue by chenzhuoyu** [Dorapower/Py-PL0-Parser#8]
1. https://github.com/Dorapower/Py-PL0-Interpreter/blob/aa2ee14f92dc64056a1713541e1c5fec30f9c6e8/src/pl0/ast_interpreter.py#L202 这个 `if` 语句缺少默认的 `else` 逻辑，当 `cond` 既不是 `OddCondition` 也不是 `ComparisonCondition` 的时候控制流会直接 fallthrough，然后导致函数返回 `None`，在 https://github.com/Dorapower/Py-PL0-Interpreter/blob/aa2ee14f92dc64056a1713541e1c5fec30f9c6e8/src/pl0/ast_interpreter.py#L149 和 https://github.com/Dorapower/Py-PL0-Interpreter/blob/aa2ee14f92dc64056a1713541e1c5fec30f9c6e8/src/pl0/ast_interpreter.py#L158 处会被认为是 `False`。虽然 `parser` 可以保证这种情况不会发生，但是这在控制流里也属于是 undefined path，最好也兜底一下，比如 `assert` 或者 `raise RuntimeError` 之类的。https://github.com/Dorapower/Py-PL0-Interpreter/blob/aa2ee14f92dc64056a1713541e1c5fec30f9c6e8/src/pl0/ast_interpreter.py#L276 处也有类似的情况。

2. https://github.com/Dorapower/Py-PL0-Interpreter/blob/aa2ee14f92dc64056a1713541e1c5fec30f9c6e8/src/pl0/icg.py#L226 由于 `IR` 的定义里 `opr` 给了默认值，这里的 `None` 可以不写的，后面也有类似的许多地方的 `None` 可以省略。

3. https://github.com/Dorapower/Py-PL0-Interpreter/blob/aa2ee14f92dc64056a1713541e1c5fec30f9c6e8/src/pl0/ic_interpreter.py#L35 这里的处理存在优化的空间，在 https://github.com/Dorapower/Py-PL0-Interpreter/blob/aa2ee14f92dc64056a1713541e1c5fec30f9c6e8/src/pl0/icg.py#L109 发射 `PROC` 指令的时候，带上一个 operand，表示这个 `proc` 有多长就可以了，不用在运行的时候去搜索，提高效率。如果不希望增加第二个 operand，可以考虑把 proc name 放在 `RET` 指令的 operand 里，这样遇到 `PROC` 的时候，`pc + PROC.opr` 就一定是 `RET` 指令，取其 operand 当做 proc name 就可以了，这样的话，`RET` 也可以改名叫 `END_PROC`。

4. https://github.com/Dorapower/Py-PL0-Interpreter/blob/aa2ee14f92dc64056a1713541e1c5fec30f9c6e8/src/pl0/ic_interpreter.py#L90 这里需要确保 `ident.type != symboltable.SymbolType.PROC`，否则会存在把 proc 当做变量值 load 的情况。如果视 proc 为一等公民，语义上是 OK 的，现有的 `CALL` 的实现看起来也能支持（不过这个支持可能是一个 bug）。严格的 PL/0 语义里面没有这种写法。

5. 同样的，在 https://github.com/Dorapower/Py-PL0-Interpreter/blob/aa2ee14f92dc64056a1713541e1c5fec30f9c6e8/src/pl0/ic_interpreter.py#L105 处，`CALL` 指令的实现没有校验 symbol 的类型，并且由于 `var` 和 `proc` 均以 `value` 字段来存储值，`CALL` 指令会把变量值当做 pc 来处理，从而导致任意代码执行，可能会带来意想不到的后果。例如以下这个程序会造成 `ic_interpreter.py` 崩溃。

```pascal
var i;
begin
    i := 100;
    call i
end.
```

由于解释器的实现将 return pc 放在了栈上，也可以通过这个 bug 来获取到，例如以下这个程序会打印 `call` 命令所在的 `pc`，一般情况下这是不可能的。

```pascal
var f, v;
begin
    f := 6;
    call f;
    v := 0;
    !v
end.
```

**Comment by chenzhuoyu** [comment]
6. https://github.com/Dorapower/Py-PL0-Interpreter/blob/aa2ee14f92dc64056a1713541e1c5fec30f9c6e8/src/pl0/ic_interpreter.py#L42 由于 `self.pc` 指向的是「下一条指令」，因此在 `_search_ret` 中，应当先获取 `current_ir` 再 `pc += 1`，否则会导致 `_search_ret` 多跳过一条指令。同时，https://github.com/Dorapower/Py-PL0-Interpreter/blob/aa2ee14f92dc64056a1713541e1c5fec30f9c6e8/src/pl0/ic_interpreter.py#L48 在函数返回前也不再需要 `pc += 1`。

**Comment by Dorapower** [comment]
All except issue#3 are fixed or optimized, issue#3 will be dealt later

Again thanks for the in-depth analysis and correction!

**Comment by Dorapower** [comment]
All except issue#3 are fixed or optimized, issue#3 will be dealt later

Again thanks for the in-depth analysis and correction!
